---
title: "Guia para ajustar modelos de curvas de crecimiento"
author: 
- Mar J.F. Ollero
- Ignacio Pardillo Gil
output: rmdformats::readthedown
---
Esta página esta asociada a la presentación: <strong> Visión Crítica del Análisis de Varianza: Modelos de Curvas de Crecimiento como Alternativa para los Diseños de Medidas Repetidas </strong> que estuvo disponible del 9 de Julio al 11 de Julio de 2021 en el V Congreso Nacional de Psicología.

El objetivo de esta página es facilitar al investigador aplicado una guía para ajustar modelos de curvas de crecimiento a datos recogidos bajo diseños longitudinales. La guía está disponible para los softwares de Rstudio y de SPSS. 

La base de datos utilizada en la guía está extraida de: <em> Hoffman, L. (2015).Longitudinal analysis: Modeling within-person fluctuation and change. Routledge. </em>

La base de datos utilizada como ejemplo recogió un total de 429 pacientes diagnosticados de fobia social severa. Pretendía comprobar el efecto de una terapia de inundación sobre dichos pacientes, la cual consistía en su participación en una exposición de 10 minutos sobre un tema previamente pactado, acudiendo como público estudiantes de prácticas. El número de sesiones aplicadas oscilaba entre 3 y 12, ya que existía la posibilidad de que los sujetos dejaran de asistir a las mismas en caso de manifestar ansiedad baja; dicho nivel era medido a través de una escala de 0 a 30 puntos que el sujeto debía completar durante la exposición en público, siendo considerada como baja una puntuación menor de 5. Por último, cabe destacar la medición de las expectativas de todos los participantes acerca de la terapia, a través de una escala del 0 al 10. 

# Modelo de curvas de crecimiento en SPSS
# Modelo de curvas de cremiento en R studio 





